# Generated by Django 5.1.1 on 2024-09-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=20)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
