# Generated by Django 5.1.1 on 2024-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_price', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
