# Generated by Django 5.1.1 on 2024-09-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='auther',
            fields=[
                ('auther_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auther_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='book1',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('published_date', models.DateField()),
                ('auther1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.auther')),
            ],
        ),
    ]
