# Generated by Django 5.1.1 on 2024-10-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='auther1',
            fields=[
                ('auther_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='book2',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.auther1')),
            ],
        ),
    ]
