# Generated by Django 5.1.1 on 2024-10-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrtation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
