# Generated by Django 5.1.1 on 2024-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_registrtation'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
