# Generated by Django 5.1.1 on 2024-10-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_courses_student_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='courses1',
        ),
    ]
