# Generated by Django 5.1.1 on 2024-10-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_login1'),
    ]

    operations = [
        migrations.CreateModel(
            name='login2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
