# Generated by Django 5.1.1 on 2024-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_login2'),
    ]

    operations = [
        migrations.CreateModel(
            name='footballmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image1/')),
            ],
        ),
    ]
